# Aykırı gözlem problem çözümü
* Silme
* Ortalama değer atama 
* Baskılama

## Silme

In [1]:
import pandas as pd
import seaborn as sns
df = sns.load_dataset("exercise")
df = df.select_dtypes(["float64", "int64"])
df = df.dropna()
df

Unnamed: 0  id  pulse
0            0   1     85
1            1   1     85
2            2   1     88
3            3   2     90
4            4   2     92
..         ...  ..    ...
85          85  29    135
86          86  29    130
87          87  30     99
88          88  30    111
89          89  30    150

[90 rows x 3 columns]

In [2]:
df_p = df["pulse"]
df_p

0      85
1      85
2      88
3      90
4      92
     ... 
85    135
86    130
87     99
88    111
89    150
Name: pulse, Length: 90, dtype: int64

In [3]:
type(df_p)  # pulse değişkeni bir seri şeklinde tutulmakta dataframe çevirme işlemi yapulur
df_p = pd.DataFrame(df_p)
type(df_p)

pandas.core.frame.DataFrame

* **aykırı gözlem değerlerinin dışında kalan değerleri ele alarak aykırı gözlemleri dataframemimizden silmiş oluruz.**
* **aykırı gözlemsiz bir DataFrame elimizde olacaktır. Aykırı gözlemlerin dısında kalmasını sağlayan "~" tilpa ifadesidir.**

In [51]:
Q1 = df_p.quantile(0.25)
Q3 = df_p.quantile(0.75)
IQR = 1.5*(Q3-Q1)
alt_sinir = Q1-IQR
ust_sinir = Q3+IQR

In [52]:
df_p.shape

(90,)

In [53]:
# tilpa "~" operatörü ile aykırı gözlem dısında kalan elemanları ele aldırır. 

In [56]:
t_df= df_p[~((df_p < alt_sinir) | (df_p > ust_sinir))]

In [62]:
t_df.shape

(80, 1)

## Ortalama Değer atama 

In [2]:
import pandas as pd
import seaborn as sns
df = sns.load_dataset("exercise")
df = df.select_dtypes(["float64", "int64"])
df = df.dropna()
df_p=df["pulse"]
Q1 = df_p.quantile(0.25)
Q3 = df_p.quantile(0.75)
IQR = 1.5*(Q3-Q1)
alt_sinir = Q1-IQR
ust_sinir = Q3+IQR

In [3]:
aykiri_tf = ((df_p > ust_sinir) | (df_p < alt_sinir))

In [4]:
#aykırı değerleri gözlemleyelim

In [5]:
df_p[aykiri_tf]

70    132
76    126
77    143
79    126
80    140
82    124
83    140
85    135
86    130
89    150
Name: pulse, dtype: int64

In [6]:
# aykırı değerlere değişlenin ortalama değerini atayalım

In [7]:
df_p.mean()

99.7

In [10]:
df_p[aykiri_tf] = df_p.mean()
df_p[aykiri_tf]

70    95.822222
76    95.822222
77    95.822222
79    95.822222
80    95.822222
82    95.822222
83    95.822222
85    95.822222
86    95.822222
89    95.822222
Name: pulse, dtype: float64

**görüldüğü üzere aykırı değerlere ortalama değer atanmıştır.**

# **Baskılama yöntemi**

### **BASKILAMA YÖNTEMİ ALT SINIR DEĞERİNE YAKIN OLAN AYKIRI GÖZLEMLERİ ALT SINIR DEĞERE EŞİTLEME VE ÜST SINIRA YAKIN OLAN AYKIRI GÖZLEMLERİ ÜST SINIRA EŞİTLEME YÖNTEMİDİR. SINIRLARA BASKILAMA**

In [29]:
import pandas as pd
import seaborn as sns
df = sns.load_dataset("exercise")
df = df.select_dtypes(["float64", "int64"])
df = df.dropna()
df_p=df["pulse"]
Q1 = df_p.quantile(0.25)
Q3 = df_p.quantile(0.75)
IQR = 1.5*(Q3-Q1)
alt_sinir = Q1-IQR
ust_sinir = Q3+IQR

**Aykırı gözlemler ust ve alt olarak ikiye ayrılır.**

In [20]:
aykiri_alt = (df_p < alt_sinir)
aykiri_ust = (df_p > ust_sinir)

**UST AYKIRI GÖZLEMLER ÜST SINIRA VE ALT SINIRA YAKIN OLAN AYKIRI GÖZLEMLER ALT SINIRA EŞİTLENİR.**

In [33]:
df_p[aykiri_alt] = alt_sinir
df_p[aykiri_ust] = ust_sinir

# **ÇOK DEĞİŞKENLİ AYKIRI GÖZLEM PROBLEM ÇÖZÜMÜ**

**_ÇOK DEĞİŞKENLİ OLARAK VERİLER GÖZLEMLENDİĞİNDE AYKIRI GÖZLEMLER ORTAYA CIKABİLMEKTEDİR.
ÖRNEĞİN EVLİLİK VE YAS DEĞİŞKENLERİ OLAN BİR DATAFRAME'DA YAS DEĞİŞKENİN ELEMANI 18 VE EVLİLİK SAYISI 4 OLMASI DURUMU AYKIRI GÖZLEM OLACAKTIR. BU DURUM GERÇEKLEŞEBİLİR YANİ OLABİLİR ANCAK GENEL VERİ DEĞERLERİNE BAKILDIĞINDA AYKIRI GÖZLEM OLARAK ELE ALINIR._**

* **LOCAL OUTLİER FACTOR**

* **_GÖZLEMLERİ BULUNDUKLARI KONUMA GÖRE YOĞUNLUK TABANLI SKORLAYARAK AYKIRI GÖZLEMLERİ TANIMLAMAMIZA OLANAK SAĞLAMAKTA._**
* _BİR NOKTANIN LOCAL YOĞUNLUĞU KOMŞU NOKTALARI İLE KARŞILAŞTIRILMAKTA. NOKTANIN LOCAL YOĞUNLUĞU KOMŞUSUNA GÖRE ANLAMLI ŞEKİLDE DÜŞÜK İSE O NOKTA AYKIRI GÖZLEM EŞİK DEĞERİ OLARAK ELE ALINMAKTADIR. YANİ BİR NOKTANIN ÇEVRESİ YOĞUN DEĞİLSE AYIKIRI GÖZLEMDİR OLARAK İFADE EDİLİR._

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns 
df = sns.load_dataset("diamonds")
df = df.select_dtypes(["float64", "int64"])
df = df.dropna()

In [54]:
from sklearn.neighbors import LocalOutlierFactor as lof

In [55]:
clf = lof(n_neighbors= 20, contamination = 0.1) # ilk parametre komşu sayısı ikinci parametre yogunluk 

In [56]:
#oluşturulan clf nesnesidf dataframe uygulanarak df dataframedeki elemanlara birer skor atamada refereans olacaktır.

In [57]:
clf.fit_predict(df)

array([-1, -1, -1, ...,  1,  1,  1])

In [58]:
# oluşturulan skorlar array olarak tutulur. negatif değerler yoğunlugun dusuk oldugu yanı aykırı gözleme yakın
#olduğu anlamındadır. DİKKAT EDİN ÇOKLU DEĞİŞKENLER ÜZERİNE İŞLEM YAPILMAKTADIR.

In [59]:
df_skor = clf.negative_outlier_factor_
df_skor

array([-1.58352526, -1.59732899, -1.62278873, ..., -1.06721815,
       -1.00809552, -1.00849038])

In [60]:
np.sort(df_skor)[0:20] # SKORLAR SIRALANDIKTAN SONRA GÖZLEMLEME

array([-8.60430658, -8.20889984, -5.86084355, -4.98415175, -4.81502092,
       -4.81502092, -4.61522833, -4.37081214, -4.29842288, -4.10492387,
       -4.0566648 , -4.01831733, -3.94882806, -3.82378797, -3.80135297,
       -3.75680919, -3.65947378, -3.59249261, -3.55564138, -3.47157375])

In [61]:
#skorlara göre bir gözlem yapıldıktan sonra bir eşik değer seçilir. 13. DEGER SEÇİLMİŞ.

In [62]:
esik_deger = np.sort(df_skor)[13]
esik_deger

-3.823787967755565

**_AYKIRI GÖZLEMLER_**

In [63]:
df_skor < esik_deger   #AYKIRI GÖZLEMLER

array([False, False, False, ..., False, False, False])

**_AYKIRI OLMAYAN GÖZLEMLER_**

In [64]:
df_skor > esik_deger  #AYKIRI OLMAYAN GÖZLEMLER

array([ True,  True,  True, ...,  True,  True,  True])

In [66]:
aykiri_ob = df[ df_skor < esik_deger]   #aykırı gözlemler
aykiri_ob

carat  depth  table  price     x      y      z
6341    1.00   44.0   53.0   4032  6.31   6.24   4.12
10377   1.09   43.0   54.0   4778  6.53   6.55   4.12
24067   2.00   58.9   57.0  12210  8.09  58.90   8.06
35633   0.29   62.8   44.0    474  4.20   4.24   2.65
36503   0.30   51.0   67.0    945  4.67   4.62   2.37
38840   0.73   70.8   55.0   1049  5.51   5.34   3.84
41918   1.03   78.2   54.0   1262  5.72   5.59   4.42
45688   0.70   71.6   55.0   1696  5.47   5.28   3.85
48410   0.51   61.8   54.7   1970  5.12   5.15  31.80
49189   0.51   61.8   55.0   2075  5.15  31.80   5.12
50773   0.81   68.8   79.0   2301  5.26   5.20   3.58
52860   0.50   79.0   73.0   2579  5.21   5.18   4.09
52861   0.50   79.0   73.0   2579  5.21   5.18   4.09

## SİLME YÖNTEMİ KULLANILDI VE AYKIRI GÖZLEMLERİN ÇIKARTILMIŞ BİR DATAFRAME KAZANILDI.

In [49]:
t_df =  df[df_skor > esik_deger]
t_df

carat  depth  table  price     x     y     z
0       0.23   61.5   55.0    326  3.95  3.98  2.43
1       0.21   59.8   61.0    326  3.89  3.84  2.31
2       0.23   56.9   65.0    327  4.05  4.07  2.31
3       0.29   62.4   58.0    334  4.20  4.23  2.63
4       0.31   63.3   58.0    335  4.34  4.35  2.75
...      ...    ...    ...    ...   ...   ...   ...
53935   0.72   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75   62.2   55.0   2757  5.83  5.87  3.64

[53926 rows x 7 columns]

# **BASKILAMA YÖNTEMİ**

**AYKIRI OLAN GÖZLEMLERE, EŞİK DEĞER OLARAK SEÇTİĞİMİZ ELEMANIN BİLGİLERİNİ AYKIRI GÖZLEMLERE TANIMLAMAKTIR. TANIMLAMADA
İNDEX HATALARI ALMAMAK İÇİN**

**SEÇİLEN EŞİK DEĞERİN ÇOK DEĞİŞKENLİ BİLGİLERİNİ ALIYORUZ.**

In [68]:
atama =  df[ df_skor == esik_deger]  
atama

carat  depth  table  price     x    y     z
31230   0.45   68.6   57.0    756  4.73  4.5  3.19

**AYKIRI GÖZLEMLERE BU DEĞİŞKENİ ATAMA İŞLEMİ YAPILARAK BASKILAMA YÖNTEMİ YAPILIR.**

In [69]:
aykiri_tf = df_skor < esik_deger

In [70]:
aykirilar = df[aykiri_tf]   #aykırı gözlemler 
aykirilar

carat  depth  table  price     x      y      z
6341    1.00   44.0   53.0   4032  6.31   6.24   4.12
10377   1.09   43.0   54.0   4778  6.53   6.55   4.12
24067   2.00   58.9   57.0  12210  8.09  58.90   8.06
35633   0.29   62.8   44.0    474  4.20   4.24   2.65
36503   0.30   51.0   67.0    945  4.67   4.62   2.37
38840   0.73   70.8   55.0   1049  5.51   5.34   3.84
41918   1.03   78.2   54.0   1262  5.72   5.59   4.42
45688   0.70   71.6   55.0   1696  5.47   5.28   3.85
48410   0.51   61.8   54.7   1970  5.12   5.15  31.80
49189   0.51   61.8   55.0   2075  5.15  31.80   5.12
50773   0.81   68.8   79.0   2301  5.26   5.20   3.58
52860   0.50   79.0   73.0   2579  5.21   5.18   4.09
52861   0.50   79.0   73.0   2579  5.21   5.18   4.09

In [71]:
#indexler hata vermemesi için aykırı gözlemlerin indexsiz şekilde array alınır.

In [72]:
res = aykirilar.to_records(index = False) #indexsiz şekilde alındı.

In [76]:
res[:] = atama.to_records(index = False)

**ŞUAN RES İSİMLİ AYKIRI GÖZLEMLERE ESİK DEGER ATANMIŞ BİR ŞEKİLDE ELİMİZDE MECVUT SUANDA ORJİNAL DATAFRAME(df)'DEKİ AYKIRI GÖZLEMLERE TAM OLARAK ATAMAA İŞLEMİ. DİKKAT EDİLMESİ GEREKEN RES İNDEXSİZ BİR HALDE. İNDEX OLUŞTURURKEN AYKIRI GÖZLEMLERİ ELE ALDIĞIMIZ aykirilar İSİMLİ DATAFRAMİN İNDEXLERİ TANIMLANARAK İNDEX ATAMA İŞLEMİDE YAPILIR.**

In [77]:
import pandas as pd
df[aykiri_tf] = pd.DataFrame(res, index = aykirilar.index)

In [78]:
df[esik_deger > df_skor]
df[aykiri_tf]

carat  depth  table  price     x    y     z
6341    0.45   68.6   57.0    756  4.73  4.5  3.19
10377   0.45   68.6   57.0    756  4.73  4.5  3.19
24067   0.45   68.6   57.0    756  4.73  4.5  3.19
35633   0.45   68.6   57.0    756  4.73  4.5  3.19
36503   0.45   68.6   57.0    756  4.73  4.5  3.19
38840   0.45   68.6   57.0    756  4.73  4.5  3.19
41918   0.45   68.6   57.0    756  4.73  4.5  3.19
45688   0.45   68.6   57.0    756  4.73  4.5  3.19
48410   0.45   68.6   57.0    756  4.73  4.5  3.19
49189   0.45   68.6   57.0    756  4.73  4.5  3.19
50773   0.45   68.6   57.0    756  4.73  4.5  3.19
52860   0.45   68.6   57.0    756  4.73  4.5  3.19
52861   0.45   68.6   57.0    756  4.73  4.5  3.19

**ORJİNAL DATAFRAMEDEKİ AYKIRI GOZLEMLERE EŞİK DEGER OLARKA SEÇTİĞİMİZ İFADENİN ÇOKLU DEĞİŞKEN DEĞERLERİ ATANMIŞ ŞEKİLDEDİR. YANİ ÇOKLU DEĞİŞKENLİ DATAFRAME AYKIRI GÖZLEMLER YOGUNLUK BULUNARAK BULUNDU. DAHA SONRA EŞİK DEĞER OLARAK SEÇİLEN İFADENİN DEĞERLERİ AYKIRI GOZLEMLERE ATANARAK BASKILAMA YONTEMİ İLE AYKIRI GÖZLEMLER UZERİNDE İŞLEM YAPILNUŞTUR**

**ÇOK DEĞİŞKENLİ DATAFRAME AYKIRI GOZLEM BULMA VE BASKILAMA YONTEMİ KULLANILMASI İLERİ SEVİYE PROGRAMLAMA BİLGİSİDİR. ÖNEMLİ**